"""
report.py — Executive Report Generator
Turns simulation results into a plain-English summary a CFO can read.
No AI needed — just smart templates.
"""


def generate_report(result, org_name="Your Organization"):
    """
    Takes a SimulationResult and returns a formatted executive summary string.
    """

    if result.p95 > 10_000_000:
        risk_level = "CRITICAL"
        risk_color = "red"
        risk_advice = "Immediate investment in security controls is strongly recommended."
    elif result.p95 > 3_000_000:
        risk_level = "HIGH"
        risk_color = "orange"
        risk_advice = "Significant exposure exists. Targeted control investments would meaningfully reduce risk."
    elif result.p95 > 500_000:
        risk_level = "MODERATE"
        risk_color = "yellow"
        risk_advice = "Risk is manageable but warrants monitoring and selective investment."
    else:
        risk_level = "LOW"
        risk_color = "green"
        risk_advice = "Current controls appear effective. Maintain existing security posture."

    report = f"""
## Executive Risk Summary — {org_name}

### Overall Risk Rating: {risk_level}

### Key Findings

**Annual Loss Exposure:**
- In a typical year (P50), losses are estimated at **${result.p50:,.0f}**
- In a bad year (P95, occurs ~1 in 20 years), losses could reach **${result.p95:,.0f}**
- In a worst-case scenario (P99), losses could exceed **${result.p99:,.0f}**

**Breach Frequency:**
- The model estimates approximately **{result.breach_rate:.1f} successful breaches per year**
- This accounts for both the volume of attacks and the effectiveness of current controls

### What This Means

The average expected annual loss is **${result.mean:,.0f}**. However, averages hide
the tail risk. The P95 figure of **${result.p95:,.0f}** represents a plausible
bad-year scenario that should be the basis for budgeting decisions.

{risk_advice}

### Recommendations

1. **Compare control scenarios** — Use the scenario comparison feature to model
   the impact of adding MFA, EDR, or security training
2. **Focus on the P95** — This is the number that belongs in board presentations
   and insurance discussions
3. **Revisit annually** — Threat landscapes change. Re-run this analysis at least
   once per year with updated inputs

### Methodology

This analysis uses the **FAIR (Factor Analysis of Information Risk)** framework
with **Monte Carlo simulation (50,000 iterations)**. Input ranges are modeled as
PERT distributions to reflect expert uncertainty. Results should be interpreted
as estimates, not predictions.

---
*Generated by Cyber Risk Quantifier — Built by Mridhul Jose*
"""
    return report, risk_level, risk_color